# Generated by Django 4.0.4 on 2022-07-18 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email_address', models.CharField(max_length=40)),
                ('phone_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=40)),
                ('zip_code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('date_of_visit', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('guest_of', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999)])),
            ],
        ),
    ]
