# Generated by Django 4.0.4 on 2022-07-18 17:46

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date_of_visit',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_of',
            field=models.IntegerField(max_length=7),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='guest',
            name='zip_code',
            field=models.IntegerField(max_length=5),
        ),
    ]
