# Generated by Django 4.0.4 on 2022-07-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_alter_guest_date_of_visit_alter_guest_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_of',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='guest',
            name='zip_code',
            field=models.IntegerField(blank=5),
        ),
    ]
