# Generated by Django 4.0.4 on 2022-07-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_alter_guest_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='street',
            new_name='address',
        ),
        migrations.AddField(
            model_name='guest',
            name='state',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
